# nginx proxy address - http://172.17.0.1:8092

name: baikal
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  baikal:
    image: ckulka/baikal:latest
    pull_policy: always
    container_name: baikal-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - baikal
    ports:
      - "172.17.0.1:8092:80"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/baikal:/var/www/baikal/config
      - ./volumes/data/baikal:/var/www/baikal/Specific

networks:
  baikal:
    external: false
